- hosts: ec2_dev
  tasks:
    - name: Importando as tarefas da máquina de desenvolvimento
      ansible.builtin.import_role:
        name: ec2-dev
        tasks_from: main  
- hosts: ec2_prod
  tasks:
    - name: Importando as tarefas da máquina de produção
      ansible.builtin.import_role:
        name: ec2-prod
        tasks_from: main